# Set seed for replicability
seed: 11

# Path or URL to sample sheet (TSV format, required columns: sample, fq or fq1, fq2, frac)
# sample - unique sample name
# run - sequencing run
# fq1 and fq2 - paths to paired-end fastq file
samples: config/samples.tsv
hexdig: False
